version: '3'

volumes:
  pgdata:
  static_files:
  uploaded_files:

services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/web/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./main:/main
      - static_files:/static_files
      - uploaded_files:/uploaded_files
    env_file:
      - ./.envs/.web
    environment:
      - FLASK_APP=web.py
    depends_on:
      - postgres
    links:
      - postgres
    command: gunicorn -w 1 web:flask_app -b :5000 --access-logfile '-'
    container_name: recsys_web_2
    restart: on-failure
    
  postgres:
    image: postgres:9.6-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./.envs/.postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    container_name: recsys_pg_2
    restart: on-failure
  
  nginx:
    container_name: nginx:1.18.0-alpine
    build:
      context: .
      dockerfile: ./dockerfiles/nginx/Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - static_files:/static_files
      - uploaded_files:/uploaded_files
    depends_on:
      - web
    container_name: recsys_nginx_2
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3.8.3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
    hostname: rabbitmq
    container_name: recsys_rmq_2
    restart: on-failure

  redis:
    image: redis:5.0.5
    ports:
      - "6379:6379"
    expose:
      - "6379"
    command: [ "redis-server", "--protected-mode", "no" ]
    hostname: redis
    container_name: recsys_redis_2
    restart: on-failure

  celery:
    build:
      context: .
      dockerfile: ./dockerfiles/web/Dockerfile
    command: celery worker -A utils.celery_tasks.main_app --loglevel=INFO
    env_file:
      - ./.envs/.web
    environment:
      - FLASK_APP=web.py
    volumes:
      - ./main:/main
    depends_on:
      - postgres
      - rabbitmq
      - redis
    links:
      - rabbitmq
      - redis
    container_name: recsys_celery_2
    restart: on-failure